[project]
name = "repl-nix-webcostestimator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.39.0",
    "trafilatura>=1.12.2",
]
