[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[theme.dark]
primaryColor = "#FF4B4B"
backgroundColor = "#262730"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
